### ISSUE TITLE
"Sketch" tutorial unclear

### ISSUE THREAD

**Issue by fyrak1s** [dune3d/dune3d-docs#6]
Hi I was following the beginners guide for Dune3D but find the directions unclear.

I got "stuck" at the point https://docs.dune3d.org/en/latest/simple-part.html#sketch

It says to draw a sketch as shown. Next is says that our sketch "has 4 degrees of freedom". However whatever I do, my sketch has 5 degrees of freedom:

![image](https://github.com/dune3d/dune3d-docs/assets/2538022/11a3481a-68de-45bd-9cd0-9d27cf726070)

I have re-read the instructions and re-did the sketch multiple times, but I cannot get the desired outcome.

EDIT: I do notice that the the top-left green square is missing the "arc" symbol (compared to the guide), however I do not know why :)

Next the guide instructs me to "Constrain the center of the arc to be on the origin of the workplane by selecting both points and invoking the “Constrain coincident” tool from the context menu.", which I do but the result looks like this:
![image](https://github.com/dune3d/dune3d-docs/assets/2538022/63b2a942-6668-46da-bf54-019da1a9f442)

Did I fail to follow the instructions or is there some missing info on how to draw the sketch?

**Comment by carrotIndustries** [comment]
> Did I fail to follow the instructions or is there some missing info on how to draw the sketch?

Your sketches are missing the arc/line tangential constraint on the top left point.

When you continue a an arc from a line or vice versa that constraint gets added automatically.
It doesn't get added automatically when closing the path on that point. I might fix that in the future.

You can also add the constraint manually by selecting the left line and the arc and invoking the 'constrain parallel' tool.

**Comment by fyrak1s** [comment]
Oh I see!

So basically for the tutorial to work, one has to start with either the bottom left or the bottom right corner.

Strangely for me, now the "arc" tangential constraint are upside down compared to the guide on https://docs.dune3d.org/en/latest/simple-part.html#sketch

![image](https://github.com/dune3d/dune3d-docs/assets/2538022/e839a17c-accc-445e-8c6c-fb3652f90bc8)

Do you know why, is that even an issue? (tried to draw it the other way round but same result)

>It doesn't get added automatically when closing the path on that point. I might fix that in the future.

Ok got it :) Maybe it should be just added to the guide how exactly to draw the lines, so it is more clear for first time users. I am fine either way now, just pointing out that it could be unclear.

**Comment by carrotIndustries** [comment]
> Do you know why, is that even an issue? (tried to draw it the other way round but same result)

The screenshots in the user guide were done with an older version where the placement was different. 

> So basically for the tutorial to work, one has to start with either the bottom left or the bottom right corner.

That or manually create the constraint.

**Comment by carrotIndustries** [comment]
> I might fix that in the future.

Done in https://github.com/dune3d/dune3d/commit/e9bbf5075513ffc9b7502ac90a8bbb780255fd2d
